[2021-10-14 16:14:15,460] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: file_upload.file_upload scheduled__2021-10-13T00:00:00+00:00 [queued]>
[2021-10-14 16:14:15,469] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: file_upload.file_upload scheduled__2021-10-13T00:00:00+00:00 [queued]>
[2021-10-14 16:14:15,469] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 16:14:15,469] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-10-14 16:14:15,469] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 16:14:15,480] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): file_upload> on 2021-10-13 00:00:00+00:00
[2021-10-14 16:14:15,484] {standard_task_runner.py:52} INFO - Started process 30604 to run task
[2021-10-14 16:14:15,489] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'file_upload', 'file_upload', 'scheduled__2021-10-13T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/file_loadin.py', '--cfg-path', '/tmp/tmp3ffupnfg', '--error-file', '/tmp/tmppa_uf8t3']
[2021-10-14 16:14:15,497] {standard_task_runner.py:77} INFO - Job 42: Subtask file_upload
[2021-10-14 16:14:15,530] {logging_mixin.py:109} INFO - Running <TaskInstance: file_upload.file_upload scheduled__2021-10-13T00:00:00+00:00 [running]> on host user-Latitude-3410
[2021-10-14 16:14:15,570] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=file_upload
AIRFLOW_CTX_TASK_ID=file_upload
AIRFLOW_CTX_EXECUTION_DATE=2021-10-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-13T00:00:00+00:00
[2021-10-14 16:14:15,572] {taskinstance.py:1686} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/user/workspace/airflow/dags/file_loadin.py", line 11, in load_excel
    pf = pd.read_excel('file.xls')
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/util/_decorators.py", line 296, in wrapper
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/io/excel/_base.py", line 304, in read_excel
    io = ExcelFile(io, engine=engine)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/io/excel/_base.py", line 867, in __init__
    self._reader = self._engines[engine](self._io)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/io/excel/_xlrd.py", line 21, in __init__
    import_optional_dependency("xlrd", extra=err_msg)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/compat/_optional.py", line 110, in import_optional_dependency
    raise ImportError(msg) from None
ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.
[2021-10-14 16:14:15,584] {taskinstance.py:1280} INFO - Marking task as UP_FOR_RETRY. dag_id=file_upload, task_id=file_upload, execution_date=20211013T000000, start_date=20211014T104415, end_date=20211014T104415
[2021-10-14 16:14:15,597] {standard_task_runner.py:91} ERROR - Failed to execute job 42 for task file_upload
Traceback (most recent call last):
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/user/workspace/airflow/dags/file_loadin.py", line 11, in load_excel
    pf = pd.read_excel('file.xls')
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/util/_decorators.py", line 296, in wrapper
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/io/excel/_base.py", line 304, in read_excel
    io = ExcelFile(io, engine=engine)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/io/excel/_base.py", line 867, in __init__
    self._reader = self._engines[engine](self._io)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/io/excel/_xlrd.py", line 21, in __init__
    import_optional_dependency("xlrd", extra=err_msg)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/compat/_optional.py", line 110, in import_optional_dependency
    raise ImportError(msg) from None
ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.
[2021-10-14 16:14:15,621] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-10-14 16:14:15,643] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-10-14 16:14:19,075] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: file_upload.file_upload manual__2021-10-14T10:44:11.854669+00:00 [queued]>
[2021-10-14 16:14:19,086] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: file_upload.file_upload manual__2021-10-14T10:44:11.854669+00:00 [queued]>
[2021-10-14 16:14:19,086] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 16:14:19,086] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-10-14 16:14:19,086] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 16:14:19,098] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): file_upload> on 2021-10-14 10:44:11.854669+00:00
[2021-10-14 16:14:19,102] {standard_task_runner.py:52} INFO - Started process 30660 to run task
[2021-10-14 16:14:19,106] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'file_upload', 'file_upload', 'manual__2021-10-14T10:44:11.854669+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/file_loadin.py', '--cfg-path', '/tmp/tmpewv1wups', '--error-file', '/tmp/tmpr1n21cz9']
[2021-10-14 16:14:19,111] {standard_task_runner.py:77} INFO - Job 43: Subtask file_upload
[2021-10-14 16:14:19,140] {logging_mixin.py:109} INFO - Running <TaskInstance: file_upload.file_upload manual__2021-10-14T10:44:11.854669+00:00 [running]> on host user-Latitude-3410
[2021-10-14 16:14:19,191] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=file_upload
AIRFLOW_CTX_TASK_ID=file_upload
AIRFLOW_CTX_EXECUTION_DATE=2021-10-14T10:44:11.854669+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-14T10:44:11.854669+00:00
[2021-10-14 16:14:19,193] {taskinstance.py:1686} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/user/workspace/airflow/dags/file_loadin.py", line 11, in load_excel
    pf = pd.read_excel('file.xls')
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/util/_decorators.py", line 296, in wrapper
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/io/excel/_base.py", line 304, in read_excel
    io = ExcelFile(io, engine=engine)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/io/excel/_base.py", line 867, in __init__
    self._reader = self._engines[engine](self._io)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/io/excel/_xlrd.py", line 21, in __init__
    import_optional_dependency("xlrd", extra=err_msg)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/compat/_optional.py", line 110, in import_optional_dependency
    raise ImportError(msg) from None
ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.
[2021-10-14 16:14:19,205] {taskinstance.py:1280} INFO - Marking task as UP_FOR_RETRY. dag_id=file_upload, task_id=file_upload, execution_date=20211014T104411, start_date=20211014T104419, end_date=20211014T104419
[2021-10-14 16:14:19,217] {standard_task_runner.py:91} ERROR - Failed to execute job 43 for task file_upload
Traceback (most recent call last):
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/user/workspace/airflow/dags/file_loadin.py", line 11, in load_excel
    pf = pd.read_excel('file.xls')
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/util/_decorators.py", line 296, in wrapper
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/io/excel/_base.py", line 304, in read_excel
    io = ExcelFile(io, engine=engine)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/io/excel/_base.py", line 867, in __init__
    self._reader = self._engines[engine](self._io)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/io/excel/_xlrd.py", line 21, in __init__
    import_optional_dependency("xlrd", extra=err_msg)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/compat/_optional.py", line 110, in import_optional_dependency
    raise ImportError(msg) from None
ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.
[2021-10-14 16:14:19,237] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-10-14 16:14:19,258] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-10-14 16:20:57,278] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: file_upload.file_upload manual__2021-10-14T10:50:53.803852+00:00 [queued]>
[2021-10-14 16:20:57,288] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: file_upload.file_upload manual__2021-10-14T10:50:53.803852+00:00 [queued]>
[2021-10-14 16:20:57,288] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 16:20:57,288] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-10-14 16:20:57,288] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 16:20:57,299] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): file_upload> on 2021-10-14 10:50:53.803852+00:00
[2021-10-14 16:20:57,302] {standard_task_runner.py:52} INFO - Started process 811 to run task
[2021-10-14 16:20:57,305] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'file_upload', 'file_upload', 'manual__2021-10-14T10:50:53.803852+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/file_loadin.py', '--cfg-path', '/tmp/tmpy6zz5aj1', '--error-file', '/tmp/tmpn61whzem']
[2021-10-14 16:20:57,308] {standard_task_runner.py:77} INFO - Job 47: Subtask file_upload
[2021-10-14 16:20:57,335] {logging_mixin.py:109} INFO - Running <TaskInstance: file_upload.file_upload manual__2021-10-14T10:50:53.803852+00:00 [running]> on host user-Latitude-3410
[2021-10-14 16:20:57,367] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=file_upload
AIRFLOW_CTX_TASK_ID=file_upload
AIRFLOW_CTX_EXECUTION_DATE=2021-10-14T10:50:53.803852+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-14T10:50:53.803852+00:00
[2021-10-14 16:20:57,369] {python.py:152} INFO - Done. Returned value was: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.
[2021-10-14 16:20:57,370] {xcom.py:333} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config.
[2021-10-14 16:20:57,370] {taskinstance.py:1686} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1502, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 2237, in xcom_push
    session=session,
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/xcom.py", line 99, in set
    value = XCom.serialize_value(value)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/xcom.py", line 330, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ImportError' is not JSON serializable
[2021-10-14 16:20:57,382] {taskinstance.py:1280} INFO - Marking task as UP_FOR_RETRY. dag_id=file_upload, task_id=file_upload, execution_date=20211014T105053, start_date=20211014T105057, end_date=20211014T105057
[2021-10-14 16:20:57,395] {standard_task_runner.py:91} ERROR - Failed to execute job 47 for task file_upload
Traceback (most recent call last):
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1502, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 2237, in xcom_push
    session=session,
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/xcom.py", line 99, in set
    value = XCom.serialize_value(value)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/xcom.py", line 330, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ImportError' is not JSON serializable
[2021-10-14 16:20:57,436] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-10-14 16:20:57,475] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-10-14 16:32:45,252] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: file_upload.file_upload manual__2021-10-14T11:02:41.939824+00:00 [queued]>
[2021-10-14 16:32:45,260] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: file_upload.file_upload manual__2021-10-14T11:02:41.939824+00:00 [queued]>
[2021-10-14 16:32:45,260] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 16:32:45,261] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-10-14 16:32:45,261] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 16:32:45,272] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): file_upload> on 2021-10-14 11:02:41.939824+00:00
[2021-10-14 16:32:45,275] {standard_task_runner.py:52} INFO - Started process 3482 to run task
[2021-10-14 16:32:45,278] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'file_upload', 'file_upload', 'manual__2021-10-14T11:02:41.939824+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/file_loadin.py', '--cfg-path', '/tmp/tmp9o6sxths', '--error-file', '/tmp/tmp9xrpq2ln']
[2021-10-14 16:32:45,281] {standard_task_runner.py:77} INFO - Job 50: Subtask file_upload
[2021-10-14 16:32:45,316] {logging_mixin.py:109} INFO - Running <TaskInstance: file_upload.file_upload manual__2021-10-14T11:02:41.939824+00:00 [running]> on host user-Latitude-3410
[2021-10-14 16:32:45,357] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=file_upload
AIRFLOW_CTX_TASK_ID=file_upload
AIRFLOW_CTX_EXECUTION_DATE=2021-10-14T11:02:41.939824+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-14T11:02:41.939824+00:00
[2021-10-14 16:32:45,358] {python.py:152} INFO - Done. Returned value was: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.
[2021-10-14 16:32:45,360] {xcom.py:333} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config.
[2021-10-14 16:32:45,360] {taskinstance.py:1686} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1502, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 2237, in xcom_push
    session=session,
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/xcom.py", line 99, in set
    value = XCom.serialize_value(value)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/xcom.py", line 330, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ImportError' is not JSON serializable
[2021-10-14 16:32:45,371] {taskinstance.py:1280} INFO - Marking task as UP_FOR_RETRY. dag_id=file_upload, task_id=file_upload, execution_date=20211014T110241, start_date=20211014T110245, end_date=20211014T110245
[2021-10-14 16:32:45,383] {standard_task_runner.py:91} ERROR - Failed to execute job 50 for task file_upload
Traceback (most recent call last):
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1502, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 2237, in xcom_push
    session=session,
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/xcom.py", line 99, in set
    value = XCom.serialize_value(value)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/xcom.py", line 330, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ImportError' is not JSON serializable
[2021-10-14 16:32:45,409] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-10-14 16:32:45,451] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-10-14 16:35:54,348] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: file_upload.file_upload manual__2021-10-14T11:05:50.986597+00:00 [queued]>
[2021-10-14 16:35:54,357] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: file_upload.file_upload manual__2021-10-14T11:05:50.986597+00:00 [queued]>
[2021-10-14 16:35:54,357] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 16:35:54,357] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-10-14 16:35:54,357] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 16:35:54,366] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): file_upload> on 2021-10-14 11:05:50.986597+00:00
[2021-10-14 16:35:54,369] {standard_task_runner.py:52} INFO - Started process 4334 to run task
[2021-10-14 16:35:54,371] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'file_upload', 'file_upload', 'manual__2021-10-14T11:05:50.986597+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/file_loadin.py', '--cfg-path', '/tmp/tmphqo0ykpw', '--error-file', '/tmp/tmpu5m4ybbc']
[2021-10-14 16:35:54,374] {standard_task_runner.py:77} INFO - Job 51: Subtask file_upload
[2021-10-14 16:35:54,398] {logging_mixin.py:109} INFO - Running <TaskInstance: file_upload.file_upload manual__2021-10-14T11:05:50.986597+00:00 [running]> on host user-Latitude-3410
[2021-10-14 16:35:54,425] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=file_upload
AIRFLOW_CTX_TASK_ID=file_upload
AIRFLOW_CTX_EXECUTION_DATE=2021-10-14T11:05:50.986597+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-14T11:05:50.986597+00:00
[2021-10-14 16:35:54,471] {logging_mixin.py:109} INFO -        first_name            startdate text
0  sushant shinde  2021-11-12 00:00:00   11
1        sushant   2021-11-13 00:00:00   12
2             NaN  2021-11-13 00:00:00   13
3             NaN                   Na   Na
4        sushant                   NaN  843
[2021-10-14 16:35:54,471] {python.py:152} INFO - Done. Returned value was:        first_name            startdate text
0  sushant shinde  2021-11-12 00:00:00   11
1        sushant   2021-11-13 00:00:00   12
2             NaN  2021-11-13 00:00:00   13
3             NaN                   Na   Na
4        sushant                   NaN  843
[2021-10-14 16:35:54,481] {xcom.py:333} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config.
[2021-10-14 16:35:54,481] {taskinstance.py:1686} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1502, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 2237, in xcom_push
    session=session,
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/xcom.py", line 99, in set
    value = XCom.serialize_value(value)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/xcom.py", line 330, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'DataFrame' is not JSON serializable
[2021-10-14 16:35:54,489] {taskinstance.py:1280} INFO - Marking task as UP_FOR_RETRY. dag_id=file_upload, task_id=file_upload, execution_date=20211014T110550, start_date=20211014T110554, end_date=20211014T110554
[2021-10-14 16:35:54,500] {standard_task_runner.py:91} ERROR - Failed to execute job 51 for task file_upload
Traceback (most recent call last):
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1502, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 2237, in xcom_push
    session=session,
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/xcom.py", line 99, in set
    value = XCom.serialize_value(value)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/xcom.py", line 330, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'DataFrame' is not JSON serializable
[2021-10-14 16:35:54,543] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-10-14 16:35:54,589] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-10-14 16:44:05,646] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: file_upload.file_upload manual__2021-10-14T11:14:01.169279+00:00 [queued]>
[2021-10-14 16:44:05,659] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: file_upload.file_upload manual__2021-10-14T11:14:01.169279+00:00 [queued]>
[2021-10-14 16:44:05,660] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 16:44:05,660] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-10-14 16:44:05,660] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 16:44:05,674] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): file_upload> on 2021-10-14 11:14:01.169279+00:00
[2021-10-14 16:44:05,677] {standard_task_runner.py:52} INFO - Started process 6609 to run task
[2021-10-14 16:44:05,680] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'file_upload', 'file_upload', 'manual__2021-10-14T11:14:01.169279+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/file_loadin.py', '--cfg-path', '/tmp/tmpuzz9guqy', '--error-file', '/tmp/tmpv7ip16ot']
[2021-10-14 16:44:05,683] {standard_task_runner.py:77} INFO - Job 54: Subtask file_upload
[2021-10-14 16:44:05,723] {logging_mixin.py:109} INFO - Running <TaskInstance: file_upload.file_upload manual__2021-10-14T11:14:01.169279+00:00 [running]> on host user-Latitude-3410
[2021-10-14 16:44:05,775] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=file_upload
AIRFLOW_CTX_TASK_ID=file_upload
AIRFLOW_CTX_EXECUTION_DATE=2021-10-14T11:14:01.169279+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-14T11:14:01.169279+00:00
[2021-10-14 16:44:05,824] {logging_mixin.py:109} INFO -        first_name            startdate text
0  sushant shinde  2021-11-12 00:00:00   11
1        sushant   2021-11-13 00:00:00   12
2             NaN  2021-11-13 00:00:00   13
3             NaN                   Na   Na
4        sushant                   NaN  843
[2021-10-14 16:44:05,824] {python.py:152} INFO - Done. Returned value was:        first_name            startdate text
0  sushant shinde  2021-11-12 00:00:00   11
1        sushant   2021-11-13 00:00:00   12
2             NaN  2021-11-13 00:00:00   13
3             NaN                   Na   Na
4        sushant                   NaN  843
[2021-10-14 16:44:05,835] {xcom.py:333} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config.
[2021-10-14 16:44:05,835] {taskinstance.py:1686} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1502, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 2237, in xcom_push
    session=session,
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/xcom.py", line 99, in set
    value = XCom.serialize_value(value)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/xcom.py", line 330, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'DataFrame' is not JSON serializable
[2021-10-14 16:44:05,848] {taskinstance.py:1280} INFO - Marking task as UP_FOR_RETRY. dag_id=file_upload, task_id=file_upload, execution_date=20211014T111401, start_date=20211014T111405, end_date=20211014T111405
[2021-10-14 16:44:05,864] {standard_task_runner.py:91} ERROR - Failed to execute job 54 for task file_upload
Traceback (most recent call last):
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1502, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 2237, in xcom_push
    session=session,
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/xcom.py", line 99, in set
    value = XCom.serialize_value(value)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/xcom.py", line 330, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'DataFrame' is not JSON serializable
[2021-10-14 16:44:05,893] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-10-14 16:44:05,920] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-10-14 16:58:45,766] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: file_upload.file_upload manual__2021-10-14T11:28:41.920632+00:00 [queued]>
[2021-10-14 16:58:45,776] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: file_upload.file_upload manual__2021-10-14T11:28:41.920632+00:00 [queued]>
[2021-10-14 16:58:45,776] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 16:58:45,777] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-10-14 16:58:45,777] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 16:58:45,793] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): file_upload> on 2021-10-14 11:28:41.920632+00:00
[2021-10-14 16:58:45,797] {standard_task_runner.py:52} INFO - Started process 10361 to run task
[2021-10-14 16:58:45,805] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'file_upload', 'file_upload', 'manual__2021-10-14T11:28:41.920632+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/file_loadin.py', '--cfg-path', '/tmp/tmp2xag3ilc', '--error-file', '/tmp/tmpjw8rj3le']
[2021-10-14 16:58:45,811] {standard_task_runner.py:77} INFO - Job 58: Subtask file_upload
[2021-10-14 16:58:45,854] {logging_mixin.py:109} INFO - Running <TaskInstance: file_upload.file_upload manual__2021-10-14T11:28:41.920632+00:00 [running]> on host user-Latitude-3410
[2021-10-14 16:58:45,892] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=file_upload
AIRFLOW_CTX_TASK_ID=file_upload
AIRFLOW_CTX_EXECUTION_DATE=2021-10-14T11:28:41.920632+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-14T11:28:41.920632+00:00
[2021-10-14 16:58:45,944] {logging_mixin.py:109} INFO -        first_name            startdate text
0  sushant shinde  2021-11-12 00:00:00   11
1        sushant   2021-11-13 00:00:00   12
2             NaN  2021-11-13 00:00:00   13
3             NaN                   Na   Na
4        sushant                   NaN  843
[2021-10-14 16:58:45,944] {python.py:152} INFO - Done. Returned value was:        first_name            startdate text
0  sushant shinde  2021-11-12 00:00:00   11
1        sushant   2021-11-13 00:00:00   12
2             NaN  2021-11-13 00:00:00   13
3             NaN                   Na   Na
4        sushant                   NaN  843
[2021-10-14 16:58:45,955] {xcom.py:333} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config.
[2021-10-14 16:58:45,955] {taskinstance.py:1686} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1502, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 2237, in xcom_push
    session=session,
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/xcom.py", line 99, in set
    value = XCom.serialize_value(value)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/xcom.py", line 330, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'DataFrame' is not JSON serializable
[2021-10-14 16:58:45,964] {taskinstance.py:1280} INFO - Marking task as UP_FOR_RETRY. dag_id=file_upload, task_id=file_upload, execution_date=20211014T112841, start_date=20211014T112845, end_date=20211014T112845
[2021-10-14 16:58:45,978] {standard_task_runner.py:91} ERROR - Failed to execute job 58 for task file_upload
Traceback (most recent call last):
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1502, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 2237, in xcom_push
    session=session,
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/xcom.py", line 99, in set
    value = XCom.serialize_value(value)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/xcom.py", line 330, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'DataFrame' is not JSON serializable
[2021-10-14 16:58:46,017] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-10-14 16:58:46,078] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-10-14 17:23:55,092] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: file_upload.file_upload manual__2021-10-14T11:48:45.369809+00:00 [queued]>
[2021-10-14 17:23:55,100] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: file_upload.file_upload manual__2021-10-14T11:48:45.369809+00:00 [queued]>
[2021-10-14 17:23:55,101] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 17:23:55,101] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-10-14 17:23:55,101] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 17:23:55,111] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): file_upload> on 2021-10-14 11:48:45.369809+00:00
[2021-10-14 17:23:55,114] {standard_task_runner.py:52} INFO - Started process 17328 to run task
[2021-10-14 17:23:55,117] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'file_upload', 'file_upload', 'manual__2021-10-14T11:48:45.369809+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/file_loadin.py', '--cfg-path', '/tmp/tmp9gv1gq41', '--error-file', '/tmp/tmpfq6vh3vr']
[2021-10-14 17:23:55,120] {standard_task_runner.py:77} INFO - Job 63: Subtask file_upload
[2021-10-14 17:23:55,144] {logging_mixin.py:109} INFO - Running <TaskInstance: file_upload.file_upload manual__2021-10-14T11:48:45.369809+00:00 [running]> on host user-Latitude-3410
[2021-10-14 17:23:55,171] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=file_upload
AIRFLOW_CTX_TASK_ID=file_upload
AIRFLOW_CTX_EXECUTION_DATE=2021-10-14T11:48:45.369809+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-14T11:48:45.369809+00:00
[2021-10-14 17:23:55,192] {logging_mixin.py:109} INFO - {"first_name":{"0":"sushant shinde","1":"sushant ","2":null,"3":null,"4":"sushant "},"startdate":{"0":1636675200000,"1":1636761600000,"2":1636761600000,"3":"Na","4":null},"text":{"0":11,"1":12,"2":13,"3":"Na","4":843}}
[2021-10-14 17:23:55,192] {python.py:152} INFO - Done. Returned value was: {"first_name":{"0":"sushant shinde","1":"sushant ","2":null,"3":null,"4":"sushant "},"startdate":{"0":1636675200000,"1":1636761600000,"2":1636761600000,"3":"Na","4":null},"text":{"0":11,"1":12,"2":13,"3":"Na","4":843}}
[2021-10-14 17:23:55,203] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=file_upload, task_id=file_upload, execution_date=20211014T114845, start_date=20211014T115355, end_date=20211014T115355
[2021-10-14 17:23:55,248] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-14 17:23:55,275] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
