[2021-10-14 16:19:18,160] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: file_upload.file_upload scheduled__2021-10-13T00:00:00+00:00 [queued]>
[2021-10-14 16:19:18,171] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: file_upload.file_upload scheduled__2021-10-13T00:00:00+00:00 [queued]>
[2021-10-14 16:19:18,171] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 16:19:18,171] {taskinstance.py:1242} INFO - Starting attempt 2 of 2
[2021-10-14 16:19:18,171] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 16:19:18,183] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): file_upload> on 2021-10-13 00:00:00+00:00
[2021-10-14 16:19:18,186] {standard_task_runner.py:52} INFO - Started process 32714 to run task
[2021-10-14 16:19:18,189] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'file_upload', 'file_upload', 'scheduled__2021-10-13T00:00:00+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/file_loadin.py', '--cfg-path', '/tmp/tmpx7js40me', '--error-file', '/tmp/tmphe8lm668']
[2021-10-14 16:19:18,192] {standard_task_runner.py:77} INFO - Job 44: Subtask file_upload
[2021-10-14 16:19:18,222] {logging_mixin.py:109} INFO - Running <TaskInstance: file_upload.file_upload scheduled__2021-10-13T00:00:00+00:00 [running]> on host user-Latitude-3410
[2021-10-14 16:19:18,256] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=file_upload
AIRFLOW_CTX_TASK_ID=file_upload
AIRFLOW_CTX_EXECUTION_DATE=2021-10-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-13T00:00:00+00:00
[2021-10-14 16:19:18,258] {taskinstance.py:1686} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/user/workspace/airflow/dags/file_loadin.py", line 11, in load_excel
    pf = pd.read_excel('file.xls')
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/util/_decorators.py", line 296, in wrapper
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/io/excel/_base.py", line 304, in read_excel
    io = ExcelFile(io, engine=engine)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/io/excel/_base.py", line 867, in __init__
    self._reader = self._engines[engine](self._io)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/io/excel/_xlrd.py", line 21, in __init__
    import_optional_dependency("xlrd", extra=err_msg)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/compat/_optional.py", line 110, in import_optional_dependency
    raise ImportError(msg) from None
ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.
[2021-10-14 16:19:18,266] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=file_upload, task_id=file_upload, execution_date=20211013T000000, start_date=20211014T104918, end_date=20211014T104918
[2021-10-14 16:19:18,279] {standard_task_runner.py:91} ERROR - Failed to execute job 44 for task file_upload
Traceback (most recent call last):
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/user/workspace/airflow/dags/file_loadin.py", line 11, in load_excel
    pf = pd.read_excel('file.xls')
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/util/_decorators.py", line 296, in wrapper
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/io/excel/_base.py", line 304, in read_excel
    io = ExcelFile(io, engine=engine)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/io/excel/_base.py", line 867, in __init__
    self._reader = self._engines[engine](self._io)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/io/excel/_xlrd.py", line 21, in __init__
    import_optional_dependency("xlrd", extra=err_msg)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/compat/_optional.py", line 110, in import_optional_dependency
    raise ImportError(msg) from None
ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.
[2021-10-14 16:19:18,320] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-10-14 16:19:18,348] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-10-14 16:19:22,486] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: file_upload.file_upload manual__2021-10-14T10:44:11.854669+00:00 [queued]>
[2021-10-14 16:19:22,499] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: file_upload.file_upload manual__2021-10-14T10:44:11.854669+00:00 [queued]>
[2021-10-14 16:19:22,499] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 16:19:22,499] {taskinstance.py:1242} INFO - Starting attempt 2 of 2
[2021-10-14 16:19:22,499] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 16:19:22,510] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): file_upload> on 2021-10-14 10:44:11.854669+00:00
[2021-10-14 16:19:22,513] {standard_task_runner.py:52} INFO - Started process 32748 to run task
[2021-10-14 16:19:22,516] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'file_upload', 'file_upload', 'manual__2021-10-14T10:44:11.854669+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/file_loadin.py', '--cfg-path', '/tmp/tmpgdmaumes', '--error-file', '/tmp/tmpbj64jv45']
[2021-10-14 16:19:22,519] {standard_task_runner.py:77} INFO - Job 45: Subtask file_upload
[2021-10-14 16:19:22,554] {logging_mixin.py:109} INFO - Running <TaskInstance: file_upload.file_upload manual__2021-10-14T10:44:11.854669+00:00 [running]> on host user-Latitude-3410
[2021-10-14 16:19:22,605] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=file_upload
AIRFLOW_CTX_TASK_ID=file_upload
AIRFLOW_CTX_EXECUTION_DATE=2021-10-14T10:44:11.854669+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-14T10:44:11.854669+00:00
[2021-10-14 16:19:22,607] {taskinstance.py:1686} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/user/workspace/airflow/dags/file_loadin.py", line 11, in load_excel
    pf = pd.read_excel('file.xls')
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/util/_decorators.py", line 296, in wrapper
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/io/excel/_base.py", line 304, in read_excel
    io = ExcelFile(io, engine=engine)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/io/excel/_base.py", line 867, in __init__
    self._reader = self._engines[engine](self._io)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/io/excel/_xlrd.py", line 21, in __init__
    import_optional_dependency("xlrd", extra=err_msg)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/compat/_optional.py", line 110, in import_optional_dependency
    raise ImportError(msg) from None
ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.
[2021-10-14 16:19:22,619] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=file_upload, task_id=file_upload, execution_date=20211014T104411, start_date=20211014T104922, end_date=20211014T104922
[2021-10-14 16:19:22,635] {standard_task_runner.py:91} ERROR - Failed to execute job 45 for task file_upload
Traceback (most recent call last):
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/user/workspace/airflow/dags/file_loadin.py", line 11, in load_excel
    pf = pd.read_excel('file.xls')
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/util/_decorators.py", line 296, in wrapper
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/io/excel/_base.py", line 304, in read_excel
    io = ExcelFile(io, engine=engine)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/io/excel/_base.py", line 867, in __init__
    self._reader = self._engines[engine](self._io)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/io/excel/_xlrd.py", line 21, in __init__
    import_optional_dependency("xlrd", extra=err_msg)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/pandas/compat/_optional.py", line 110, in import_optional_dependency
    raise ImportError(msg) from None
ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.
[2021-10-14 16:19:22,647] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-10-14 16:19:22,670] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-10-14 16:26:02,817] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: file_upload.file_upload manual__2021-10-14T10:50:53.803852+00:00 [queued]>
[2021-10-14 16:26:02,832] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: file_upload.file_upload manual__2021-10-14T10:50:53.803852+00:00 [queued]>
[2021-10-14 16:26:02,832] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 16:26:02,832] {taskinstance.py:1242} INFO - Starting attempt 2 of 2
[2021-10-14 16:26:02,832] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 16:26:02,847] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): file_upload> on 2021-10-14 10:50:53.803852+00:00
[2021-10-14 16:26:02,850] {standard_task_runner.py:52} INFO - Started process 1965 to run task
[2021-10-14 16:26:02,853] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'file_upload', 'file_upload', 'manual__2021-10-14T10:50:53.803852+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/file_loadin.py', '--cfg-path', '/tmp/tmp63bo5gwq', '--error-file', '/tmp/tmp92265csm']
[2021-10-14 16:26:02,856] {standard_task_runner.py:77} INFO - Job 48: Subtask file_upload
[2021-10-14 16:26:02,905] {logging_mixin.py:109} INFO - Running <TaskInstance: file_upload.file_upload manual__2021-10-14T10:50:53.803852+00:00 [running]> on host user-Latitude-3410
[2021-10-14 16:26:02,982] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=file_upload
AIRFLOW_CTX_TASK_ID=file_upload
AIRFLOW_CTX_EXECUTION_DATE=2021-10-14T10:50:53.803852+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-14T10:50:53.803852+00:00
[2021-10-14 16:26:02,987] {python.py:152} INFO - Done. Returned value was: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.
[2021-10-14 16:26:02,989] {xcom.py:333} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config.
[2021-10-14 16:26:02,989] {taskinstance.py:1686} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1502, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 2237, in xcom_push
    session=session,
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/xcom.py", line 99, in set
    value = XCom.serialize_value(value)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/xcom.py", line 330, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ImportError' is not JSON serializable
[2021-10-14 16:26:03,007] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=file_upload, task_id=file_upload, execution_date=20211014T105053, start_date=20211014T105602, end_date=20211014T105603
[2021-10-14 16:26:03,032] {standard_task_runner.py:91} ERROR - Failed to execute job 48 for task file_upload
Traceback (most recent call last):
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1502, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 2237, in xcom_push
    session=session,
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/xcom.py", line 99, in set
    value = XCom.serialize_value(value)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/xcom.py", line 330, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ImportError' is not JSON serializable
[2021-10-14 16:26:03,052] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-10-14 16:26:03,087] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-10-14 16:40:57,424] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: file_upload.file_upload manual__2021-10-14T11:05:50.986597+00:00 [queued]>
[2021-10-14 16:40:57,434] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: file_upload.file_upload manual__2021-10-14T11:05:50.986597+00:00 [queued]>
[2021-10-14 16:40:57,434] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 16:40:57,434] {taskinstance.py:1242} INFO - Starting attempt 2 of 2
[2021-10-14 16:40:57,434] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 16:40:57,444] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): file_upload> on 2021-10-14 11:05:50.986597+00:00
[2021-10-14 16:40:57,447] {standard_task_runner.py:52} INFO - Started process 5788 to run task
[2021-10-14 16:40:57,450] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'file_upload', 'file_upload', 'manual__2021-10-14T11:05:50.986597+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/file_loadin.py', '--cfg-path', '/tmp/tmpfy0fd7q7', '--error-file', '/tmp/tmpg7a6gtnl']
[2021-10-14 16:40:57,453] {standard_task_runner.py:77} INFO - Job 52: Subtask file_upload
[2021-10-14 16:40:57,480] {logging_mixin.py:109} INFO - Running <TaskInstance: file_upload.file_upload manual__2021-10-14T11:05:50.986597+00:00 [running]> on host user-Latitude-3410
[2021-10-14 16:40:57,526] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=file_upload
AIRFLOW_CTX_TASK_ID=file_upload
AIRFLOW_CTX_EXECUTION_DATE=2021-10-14T11:05:50.986597+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-14T11:05:50.986597+00:00
[2021-10-14 16:40:57,566] {logging_mixin.py:109} INFO -        first_name            startdate text
0  sushant shinde  2021-11-12 00:00:00   11
1        sushant   2021-11-13 00:00:00   12
2             NaN  2021-11-13 00:00:00   13
3             NaN                   Na   Na
4        sushant                   NaN  843
[2021-10-14 16:40:57,566] {python.py:152} INFO - Done. Returned value was:        first_name            startdate text
0  sushant shinde  2021-11-12 00:00:00   11
1        sushant   2021-11-13 00:00:00   12
2             NaN  2021-11-13 00:00:00   13
3             NaN                   Na   Na
4        sushant                   NaN  843
[2021-10-14 16:40:57,576] {xcom.py:333} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config.
[2021-10-14 16:40:57,576] {taskinstance.py:1686} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1502, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 2237, in xcom_push
    session=session,
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/xcom.py", line 99, in set
    value = XCom.serialize_value(value)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/xcom.py", line 330, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'DataFrame' is not JSON serializable
[2021-10-14 16:40:57,584] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=file_upload, task_id=file_upload, execution_date=20211014T110550, start_date=20211014T111057, end_date=20211014T111057
[2021-10-14 16:40:57,594] {standard_task_runner.py:91} ERROR - Failed to execute job 52 for task file_upload
Traceback (most recent call last):
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1502, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 2237, in xcom_push
    session=session,
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/xcom.py", line 99, in set
    value = XCom.serialize_value(value)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/xcom.py", line 330, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'DataFrame' is not JSON serializable
[2021-10-14 16:40:57,621] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-10-14 16:40:57,643] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-10-14 16:49:09,164] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: file_upload.file_upload manual__2021-10-14T11:14:01.169279+00:00 [queued]>
[2021-10-14 16:49:09,174] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: file_upload.file_upload manual__2021-10-14T11:14:01.169279+00:00 [queued]>
[2021-10-14 16:49:09,175] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 16:49:09,175] {taskinstance.py:1242} INFO - Starting attempt 2 of 2
[2021-10-14 16:49:09,175] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 16:49:09,191] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): file_upload> on 2021-10-14 11:14:01.169279+00:00
[2021-10-14 16:49:09,195] {standard_task_runner.py:52} INFO - Started process 8215 to run task
[2021-10-14 16:49:09,198] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'file_upload', 'file_upload', 'manual__2021-10-14T11:14:01.169279+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/file_loadin.py', '--cfg-path', '/tmp/tmpy6eqkhkk', '--error-file', '/tmp/tmpj1h6unsr']
[2021-10-14 16:49:09,202] {standard_task_runner.py:77} INFO - Job 55: Subtask file_upload
[2021-10-14 16:49:09,233] {logging_mixin.py:109} INFO - Running <TaskInstance: file_upload.file_upload manual__2021-10-14T11:14:01.169279+00:00 [running]> on host user-Latitude-3410
[2021-10-14 16:49:09,282] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=file_upload
AIRFLOW_CTX_TASK_ID=file_upload
AIRFLOW_CTX_EXECUTION_DATE=2021-10-14T11:14:01.169279+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-14T11:14:01.169279+00:00
[2021-10-14 16:49:09,328] {logging_mixin.py:109} INFO -        first_name            startdate text
0  sushant shinde  2021-11-12 00:00:00   11
1        sushant   2021-11-13 00:00:00   12
2             NaN  2021-11-13 00:00:00   13
3             NaN                   Na   Na
4        sushant                   NaN  843
[2021-10-14 16:49:09,329] {python.py:152} INFO - Done. Returned value was:        first_name            startdate text
0  sushant shinde  2021-11-12 00:00:00   11
1        sushant   2021-11-13 00:00:00   12
2             NaN  2021-11-13 00:00:00   13
3             NaN                   Na   Na
4        sushant                   NaN  843
[2021-10-14 16:49:09,347] {xcom.py:333} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config.
[2021-10-14 16:49:09,347] {taskinstance.py:1686} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1502, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 2237, in xcom_push
    session=session,
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/xcom.py", line 99, in set
    value = XCom.serialize_value(value)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/xcom.py", line 330, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'DataFrame' is not JSON serializable
[2021-10-14 16:49:09,360] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=file_upload, task_id=file_upload, execution_date=20211014T111401, start_date=20211014T111909, end_date=20211014T111909
[2021-10-14 16:49:09,382] {standard_task_runner.py:91} ERROR - Failed to execute job 55 for task file_upload
Traceback (most recent call last):
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1502, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 2237, in xcom_push
    session=session,
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/xcom.py", line 99, in set
    value = XCom.serialize_value(value)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/xcom.py", line 330, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'DataFrame' is not JSON serializable
[2021-10-14 16:49:09,411] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-10-14 16:49:09,453] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-10-14 17:03:49,510] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: file_upload.file_upload manual__2021-10-14T11:28:41.920632+00:00 [queued]>
[2021-10-14 17:03:49,521] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: file_upload.file_upload manual__2021-10-14T11:28:41.920632+00:00 [queued]>
[2021-10-14 17:03:49,521] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 17:03:49,521] {taskinstance.py:1242} INFO - Starting attempt 2 of 2
[2021-10-14 17:03:49,521] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 17:03:49,533] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): file_upload> on 2021-10-14 11:28:41.920632+00:00
[2021-10-14 17:03:49,536] {standard_task_runner.py:52} INFO - Started process 12713 to run task
[2021-10-14 17:03:49,540] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'file_upload', 'file_upload', 'manual__2021-10-14T11:28:41.920632+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/file_loadin.py', '--cfg-path', '/tmp/tmp3xy5b0v5', '--error-file', '/tmp/tmphxqwmxxo']
[2021-10-14 17:03:49,544] {standard_task_runner.py:77} INFO - Job 59: Subtask file_upload
[2021-10-14 17:03:49,578] {logging_mixin.py:109} INFO - Running <TaskInstance: file_upload.file_upload manual__2021-10-14T11:28:41.920632+00:00 [running]> on host user-Latitude-3410
[2021-10-14 17:03:49,614] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=file_upload
AIRFLOW_CTX_TASK_ID=file_upload
AIRFLOW_CTX_EXECUTION_DATE=2021-10-14T11:28:41.920632+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-14T11:28:41.920632+00:00
[2021-10-14 17:03:49,650] {logging_mixin.py:109} INFO -        first_name            startdate text
0  sushant shinde  2021-11-12 00:00:00   11
1        sushant   2021-11-13 00:00:00   12
2             NaN  2021-11-13 00:00:00   13
3             NaN                   Na   Na
4        sushant                   NaN  843
[2021-10-14 17:03:49,651] {python.py:152} INFO - Done. Returned value was:        first_name            startdate text
0  sushant shinde  2021-11-12 00:00:00   11
1        sushant   2021-11-13 00:00:00   12
2             NaN  2021-11-13 00:00:00   13
3             NaN                   Na   Na
4        sushant                   NaN  843
[2021-10-14 17:03:49,660] {xcom.py:333} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config.
[2021-10-14 17:03:49,660] {taskinstance.py:1686} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1502, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 2237, in xcom_push
    session=session,
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/xcom.py", line 99, in set
    value = XCom.serialize_value(value)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/xcom.py", line 330, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'DataFrame' is not JSON serializable
[2021-10-14 17:03:49,669] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=file_upload, task_id=file_upload, execution_date=20211014T112841, start_date=20211014T113349, end_date=20211014T113349
[2021-10-14 17:03:49,679] {standard_task_runner.py:91} ERROR - Failed to execute job 59 for task file_upload
Traceback (most recent call last):
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1502, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 2237, in xcom_push
    session=session,
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/xcom.py", line 99, in set
    value = XCom.serialize_value(value)
  File "/home/user/workspace/airflow/airflow_env/lib/python3.6/site-packages/airflow/models/xcom.py", line 330, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'DataFrame' is not JSON serializable
[2021-10-14 17:03:49,711] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-10-14 17:03:49,757] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
